### ISSUE TITLE
Data Preparation for readRABBIT

### ISSUE THREAD

**Issue by yan-cheng-lin** [Biometris/statgenMPP#2]
Hi,

First, thank you for making this useful software.
I am currently working on a 8 founder MAGIC population of maize for my PhD.
I would like to input my data via readRABBIT().
However, I could not find clear definition of the data format in both yours and RABBIT github.
Especially, like the funnelcode in pedfile, and the explanation of infile.
Would it be possible for you to provide it?

Thank you in advance.

Best regards,
Yan-Cheng

**Comment by BartJanvanRossum** [comment]
Hi,

The readRABBITMPP() function takes as infile the output file as it is produced as output by RABBIT. This file format is quite complex, but there is an example contained in the package. 
Running this will give you the location of the file on your system:
```r
system.file("extdata/barley", "barley_magicReconstruct.zip",
                       package = "statgenMPP")
```
However it is easiest to just run RABBIT and directly use its output as infile.
The format of the pedFile is the same as that used by RABBIT. It is described in section 1.4 of the manual, available at https://github.com/chaozhi/RABBIT/blob/master/RABBIT_Manual/RABBIT%20Manual.pdf

I hope this helps

Best regards,
Bart-Jan

**Comment by yan-cheng-lin** [comment]
Hi Bart-Jan,

Thank you for your reply.
I wanted to use the custmized genotype probabilities, rather than taking the results from RABBIT.
I eventually solve the problem by creating the output of calcIBD in statgenIBD and then createGDataMPP, even though I still couldn't make the RABBIT files.

Best regards,
Yan-Cheng
